name: Run Selenium Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Install dependencies
      run: |
        sudo apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager

    - name: Start application
      run: |
        python app.py &
        sleep 3  # give the application some time to start

    - name: Run tests
      run: |
        xvfb-run python -m unittest submit_test.py
      env:
        CHROME_BIN: ${{ steps.setup-chrome.outputs.executablePath }}
